import type { Metadata } from 'next'
import { Open_Sans, Raleway } from 'next/font/google'
import './globals.css'
import Header from '@/components/header/Header'

const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-open-sans',
})

const raleway = Raleway({
  subsets: ['latin'],
  weight: ['600', '800'],
  variable: '--font-raleway',
})

export const metadata: Metadata = {
  title: 'Fruitables',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br" className={`${openSans.variable} ${raleway.variable}`}>
      <body className="container mx-auto min-h-screen px-4 pt-24 font-openSans">
        <Header />
        {children}
      </body>
    </html>
  )
}
